/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reporting;

import java.awt.BorderLayout;
import java.awt.Color;
//import javafx.scene.paint.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.event.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import projethopital.ChoixAction;
import projethopital.Connexion;
import AjouterSupp.*;
import org.jfree.chart.ChartFactory;

/**
 *
 * @author tomhuet
 */
public class Reporting extends JFrame {
    
    public Reporting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                           
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelChart = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SERomand", 0, 70)); // NOI18N
        jLabel2.setText("Reporting");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 380, 110);

        panelChart.setBackground(new java.awt.Color(153, 153, 153));
        panelChart.setForeground(new java.awt.Color(255, 255, 255));
        panelChart.setOpaque(false);
        panelChart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelChart);
        panelChart.setBounds(140, 200, 930, 510);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1090, 680, 130, 40);

        jButton2.setText("Nombre de lit par service");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 130, 260, 60);

        jButton3.setText("Quantité de specialite dans l'hopitale");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 130, 270, 60);

        jButton4.setText("Nombre de malade par docteur");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(900, 130, 250, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
    }                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new ChoixAction().setVisible(true);
        this.setVisible(false);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultCategoryDataset graph = new DefaultCategoryDataset();
        graph.setValue(4, "Nombre","REA");
        graph.setValue(11, "Nombre","CAR");
        graph.setValue(25, "Nombre","CHG");
        
        
        JFreeChart barchart = ChartFactory.createBarChart("Nombre de lit par service", "Service", "Nombre", graph, PlotOrientation.VERTICAL, false,true, false);
        CategoryPlot brchrt = barchart.getCategoryPlot();
        brchrt.setRangeGridlinePaint(Color.gray);
        
        ChartPanel barPanel = new ChartPanel(barchart);
        panelChart.removeAll();
        panelChart.add(barPanel,BorderLayout.CENTER);
        panelChart.validate();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultCategoryDataset graph = new DefaultCategoryDataset();
        graph.setValue(8, "Nombre","Cardiologue");
        graph.setValue(5, "Nombre","Pneumologue");
        graph.setValue(4, "Nombre","Traumatologue");
        graph.setValue(4, "Nombre","Orthopediste");
        graph.setValue(3, "Nombre","Anesthésiste");
        graph.setValue(4, "Nombre","Radiologue");
        
        JFreeChart barchart = ChartFactory.createBarChart("Quantité de specialite dans l'hopitale", "Specialite", "Nombre", graph, PlotOrientation.VERTICAL, false,true, false);
        CategoryPlot brchrt = barchart.getCategoryPlot();
        brchrt.setRangeGridlinePaint(Color.gray);
        
        ChartPanel barPanel = new ChartPanel(barchart);
        panelChart.removeAll();
        panelChart.add(barPanel,BorderLayout.CENTER);
        panelChart.validate();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultCategoryDataset graph = new DefaultCategoryDataset();
        graph.setValue(6, "Nombre","4");//numero du docteur
        graph.setValue(6, "Nombre","7");
        graph.setValue(4, "Nombre","8");
        graph.setValue(5, "Nombre","10");
        graph.setValue(3, "Nombre","19");
        graph.setValue(1, "Nombre","24");
        
        
        JFreeChart barchart = ChartFactory.createBarChart("Nombre de malade par docteur", "Docteur", "Nombre", graph, PlotOrientation.VERTICAL, false,true, false);
        CategoryPlot brchrt = barchart.getCategoryPlot();
        brchrt.setRangeGridlinePaint(Color.gray);
        
        ChartPanel barPanel = new ChartPanel(barchart);
        panelChart.removeAll();
        panelChart.add(barPanel,BorderLayout.CENTER);
        panelChart.validate();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Reporting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelChart;
    // End of variables declaration  
    
}
